### ISSUE TITLE
Few 3DS titles listed as EUR/JPN when they should be ALL

### ISSUE THREAD

**Issue by Nomelas** [FailedShack/USBHelperLauncher#11]
Pokémon Rumble World
Pokémon Shuffle
Code Name S.T.E.A.M.
Kirby's Blowout Blast (listed as JPN under the title 'カービィのすいこみ大作戦' - but it's actually ALL)

**Comment by gekiyakupl** [comment]
Will it be possible to download 3ds games in the future?
