### ISSUE TITLE
App crashes When Injecting

### ISSUE THREAD

**Issue by CVFireDragon** [FailedShack/USBHelperLauncher#12]
Idk how this happened, but one day it just started doing this.

**Comment by FailedShack** [comment]
I need more information to reproduce this issue. Please provide the following:

* The name of the game you were trying to inject and from which region.
* A screenshot of the error message if there is any.
* If there is an error message, a log of USBHelperLauncher at the moment of the error.

**Comment by CVFireDragon** [comment]
It fixed by re-installing
