### ISSUE TITLE
503 Server unavailable error

### ISSUE THREAD

**Issue by rydale** [FailedShack/USBHelperLauncher#16]
I am getting a 503 Server unavailable error when Wii U USB Helper is loading. If I choose continue, the app still loads, but is unusable. It appears to be missing content, and there is a modal splash screen or something blocking half of the app.

Error while loading:
![image](https://user-images.githubusercontent.com/22924281/44195401-c9e93f80-a0ed-11e8-93c9-5ca42093900a.png)

Happens at this point:
![image](https://user-images.githubusercontent.com/22924281/44195508-22b8d800-a0ee-11e8-8afa-47d1960a9e8f.png)

![image](https://user-images.githubusercontent.com/22924281/44195554-3b28f280-a0ee-11e8-886f-0c42ab3cfd04.png)
![image](https://user-images.githubusercontent.com/22924281/44195578-4e3bc280-a0ee-11e8-81ba-c6ab81cf2ba3.png)

Thank you

**Comment by rydale** [comment]
Ehh, I spoke too soon. I can't download any games. I get a 503 error.

**Comment by FailedShack** [comment]
@rydale This is not a place for assistance.
Find the launcher's tray icon and go to Advanced -> Clear Install.
