### ISSUE TITLE
404 Error while Wii/Gamecube Iso Download

### ISSUE THREAD

**Issue by DerDominik** [FailedShack/USBHelperLauncher#2]
Great work, that USBHelper is still useable :-)
But I found a little problem.
I choosed a GameCube Game, but after first step (select ISO file) I got a 404-error.

![unbenannt](https://user-images.githubusercontent.com/16927324/40774793-d1cd42e0-64c6-11e8-81e6-6aa079280f5b.png)

Maybe this is fixable?

**Comment by DerDominik** [comment]
No problem, your workaround with the attached zip is working great!
Thanks for your fast help :-)

**Comment by DerDominik** [comment]
Sorry, but there's one problem with the Downloads :-/
![unbenannt](https://user-images.githubusercontent.com/16927324/40840440-f1ee27de-65a6-11e8-97e1-0a21f45a5330.png)

Now I'm trying to download Mario Party 8 (Wii Game), and there's a similar error

**Comment by FailedShack** [comment]
Please attach a debug message when reporting issues, so that I can assess what's going on.
Right click the notification icon on the taskbar and select 'Report Issue'.

**Comment by DerDominik** [comment]
Sorry for my late reply.
After a restart of the program everything was fine :-)

**Comment by FailedShack** [comment]
Fixed by https://github.com/FailedShack/USBHelperLauncher/commit/fda98003bb181c5a5317d7a6e27e97270aabbc9a
