### ISSUE TITLE
Unable to sync with Wii U

### ISSUE THREAD

**Issue by leoleotte** [FailedShack/USBHelperLauncher#20]
By using an HTTP proxy, the app can't communicate with a Wii U running the "Wii U USB Helper Transfer Tool" homebrew.

There is an error when using the option "Send to Wii U" and it doesn't sync your installed games by giving this error: "Sync Failed (Is Mocha Running?)". I tried with normal Haxchi and with Mocha and both give the same error.

Is this something by-passable by this launcher? I really liked these features!

**Comment by leoleotte** [comment]
Here are some screenshots for the mentioned errors:

![image](https://user-images.githubusercontent.com/5093266/44959978-ad128180-aecd-11e8-940c-1c7b2b558196.png)

![image](https://user-images.githubusercontent.com/5093266/44959985-c3204200-aecd-11e8-9363-5536dde37591.png)

**Comment by leoleotte** [comment]
After updating to the latest version of the homebrew transfer tool and the launcher, it's syncing normally now... sorry!

**Comment by FailedShack** [comment]
Indeed this was an issue that was fixed with [0.11](https://github.com/FailedShack/USBHelperLauncher/releases/tag/0.11). Previously FTP requests were shoehorned into the HTTP proxy which of course makes no sense.
