### ISSUE TITLE
any help with this issue, thanks man..

### ISSUE THREAD

**Issue by ratmandom** [FailedShack/USBHelperLauncher#21]
![wii u usb helper](https://user-images.githubusercontent.com/37990439/45389505-0be5a280-b614-11e8-8990-3a156bc8ff61.jpg)

**Comment by FailedShack** [comment]
This is not a place for assistance. Check the [Reddit thread](https://www.reddit.com/r/CemuPiracy/comments/8gj8z8/workaround_download_and_run_wii_u_usb_helper/) or [join the Discord](https://discord.io/usbhelperlauncher).
