### ISSUE TITLE
Game Info in wrong language

### ISSUE THREAD

**Issue by cawoodm** [FailedShack/USBHelperLauncher#22]
I'm in Germany but I want stuff in English. The UI is showing some content (specifically game info texts) in German. My Windows 10 setup is all English so I'm not sure where this is coming from.

According to Fiddler, request to yandex.com are getting the "Accept-Language" header of "de-DE".

![image](https://user-images.githubusercontent.com/498834/46681554-c05eee00-cbeb-11e8-9941-46a835252bfd.png)

**Comment by gekiyakupl** [comment]
I am from poland and had same issue. There were 2 versions of this game so maybe it is just german ver.
