### ISSUE TITLE
USBHelperLaucher keeps getting deleted

### ISSUE THREAD

**Issue by oqwe** [FailedShack/USBHelperLauncher#23]
For some reason, USBHelperLaucher deleted itself, so I decided to try and put back the exe in, but now for some reason I have no permission to, and it won't tell me why. Do you know what's the issue?

**Comment by FailedShack** [comment]
Sounds like your antivirus is interferring. Try disabling it.
However this is not the correct place for assistance. [Join the Discord](https://discord.io/usbhelperlauncher).
