### ISSUE TITLE
Wii U USB Helper Go!

### ISSUE THREAD

**Issue by zerofalcon** [FailedShack/USBHelperLauncher#25]
Hi! thanks for maintaining this  nice piece of software. By now I'm not having a pc near me so my question is: is there a patch or a setting to update the android apk to work again? or we just have to wait for those title key sites to be online? Thanks

**Comment by FailedShack** [comment]
Yesterday I updated the APK on the Reddit post with a new version that uses an archived version of the title key site. However, against all odds the original title key site has come back online, so you may continue to use the previous version of the APK.
