### ISSUE TITLE
Cant launch the Launcher

### ISSUE THREAD

**Issue by Meowcat285** [FailedShack/USBHelperLauncher#26]
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
   at USBHelperLauncher.Program.Main(String[] args)

Is the error

**Comment by FailedShack** [comment]
Did you unpack USBHelperLauncher in the same folder as Wii U USB Helper?
This is not the correct place for assistance. [Join the Discord](https://discord.io/usbhelperlauncher).
