### ISSUE TITLE
All of a sudden Wii U USB Helper can't get any titlekeys anymore

### ISSUE THREAD

**Issue by OldGnashburg** [FailedShack/USBHelperLauncher#27]
I've been using your Launcher Workaround for about a month, I was even using earlier last night. Now when I got try to use it, whenever I put in the Title Key site it gives me this message.
There was an error while trying to fetch the titlekeys from wiiu.titlekeys.gq (the site is probably down). No backup was found. Unfortunately the app cannot work without it.

**Comment by FailedShack** [comment]
This is not the correct place for assistance. [Join the Discord](https://discord.io/usbhelperlauncher).
