### ISSUE TITLE
Injector Tool

### ISSUE THREAD

**Issue by HenryTheHover** [FailedShack/USBHelperLauncher#32]
When using the Helper's injector tool which allows games not on the eShop (e.g. Mario Kart Wii) to be started from the Wii U home menu, after providing an ISO for the game, it results in an error and the injection is stopped. 
![image](https://user-images.githubusercontent.com/45914726/50053031-cb6f5680-0125-11e9-893c-02b663808d31.png)
The console:
![image](https://user-images.githubusercontent.com/45914726/50053045-0d989800-0126-11e9-94e7-bf0a95220025.png)
I can't use the report an issue because that isn't working?

**Comment by FailedShack** [comment]
Fixed as of 3cf889687846811606279900b60c2b056c7a02f9
