### ISSUE TITLE
How do I change the language?

### ISSUE THREAD

**Issue by Morilli** [FailedShack/USBHelperLauncher#56]
I don't like the translations. Is there a way to disable them / change the language?

**Comment by FailedShack** [comment]
You can change your preferred language by right-clicking the launcher's tray icon.

<img width="331" alt="Language" src="https://user-images.githubusercontent.com/39192928/72224792-9169c180-357e-11ea-9309-269052aa5d40.png">

**Comment by Morilli** [comment]
Thanks
