### ISSUE TITLE
Cemu detected a DLC installed at a wrong or outdated location

### ISSUE THREAD

**Issue by megapro17** [FailedShack/USBHelperLauncher#57]
So how to fix this? If I click yes, on the next launch USB Helper will again unpack DLC to the wrong location.

**Comment by FailedShack** [comment]
The following code is responsible for setting the extraction directory:
https://github.com/FailedShack/WiiU_USB_Helper/blob/8c474c06f149153202a4289507daa97322f25080/NusHelper/Emulators/Cemu.cs#L41

This would need to be patched in order to use the new location and perhaps make it configurable.

**Comment by megapro17** [comment]
```
public string DlcPath
    {
      get
      {
        return System.IO.Path.Combine(this.String_4, "mlc01", "usr", "title", "0005000e", this.gclass30_0.TitleId.High.ToLower());

      }
```
Seems like easy fix. Can you compile for I can test it?

**Comment by FailedShack** [comment]
Well, the thing is that this is an issue present in Wii U USB Helper itself.
We don't actually have its source code, what I linked is just a decompilation for it and won't compile.
It needs a patch, similar to [these](https://github.com/FailedShack/USBHelperLauncher/tree/master/USBHelperInjector/Patches). They make use of [Harmony](https://github.com/pardeike/Harmony), our runtime patching library.

I'll create one when I get the chance or feel free to open a PR if you want to look into it yourself.

**Comment by megapro17** [comment]
Maybe it is better to recreate a whole program from decompiled code, instead of making infinity amount of patches?

**Comment by FailedShack** [comment]
> 
> 
> Maybe it is better to recreate a whole program from decompiled code, instead of making infinity amount of patches?

Maybe.

**Comment by Pythonic-Rainbow** [comment]
Actually will you plan to create a new Wii U downloader from the ground up? I am just curious because I believe quite a big amount of time is spent on trying to create patches

**Comment by megapro17** [comment]
Wow, I even dropped playing botw... Boring and lagging
