### ISSUE TITLE
Stuck on "USB Helper is preparing the ticket cache

### ISSUE THREAD

**Issue by Virtualistik** [FailedShack/USBHelperLauncher#6]
When usb helper is opened, it hangs on "USB Helper is preparing the ticket cache". When I force close the app it says "System.exception. No titles available. Please check your ticket source"

**Comment by Virtualistik** [comment]
Fixed by going to the tray while the launcher was stuck, right click>advanced>clear install

**Comment by cemerson** [comment]
Someone mentioned titlekeys.ovh works now instead.
