### ISSUE TITLE
Yesterday it worked today stuck at 'fetching the title keys'

### ISSUE THREAD

**Issue by MediaMaquina** [FailedShack/USBHelperLauncher#60]
The title key site works. i don't know what's up.
Also yesterday i played new super mario u but on CEMU it doesn't show up, other games do. What could cause that?

**Comment by FailedShack** [comment]
USBHelperInstaller only deals with installation. This issue is about the launcher.
In any case, this is not the place for assistance. Please join our [Discord](https://discord.io/usbhelperlauncher) for that.
