### ISSUE TITLE
3ds games downloads are blocked

### ISSUE THREAD

**Issue by zahi112** [FailedShack/USBHelperLauncher#62]
3ds games downloads are blocked it says nintendo has additional protection over these files cannot download please fix it.

**Comment by EustaceCS** [comment]
@zahi112 , unless someone would be able to pay few million bucks for infiltrating Nintendo's 3DS server maintenance team, it's unlikely to happen.
(or, slightly less million bucks to a hacker for finding a way to mock new Nintendo-side protection)
Reference:
https://www.reddit.com/r/CemuPiracy/comments/bszm0p/how_to_set_up_wii_u_usb_helper_after_its/
> As of system update 11.8.0-41, the 3DS sends new required title information in download requests to Nintendo's servers, which includes the title's ticket. Tickets are signed and cannot be feasibly forged, they also contain data such as original console id, which means that if shared, they can easily be blacklisted and the console of origin banned.
