### ISSUE TITLE
.exe.config file does not save

### ISSUE THREAD

**Issue by wiiutitlekeys** [FailedShack/USBHelperLauncher#63]
The config never changes, even after launch. The "Path" and "TicketsPath" always remain empty, and "Region" always says "NONE". Is there anyway to fix this?

**Comment by shiftinv** [comment]
The `.exe.config` file in the install directory is only used for application-scoped settings and can't be changed at runtime (i.e. it mostly contains default settings). Any changes made to (user-scoped) settings at runtime are stored in a `user.config` file, which can be found at `%localappdata%\Hikari06\WiiU_USB_Helper_.exe_Url_<hash>\1.0.0.0\user.config`; you can find some more information about it [here](https://docs.microsoft.com/en-us/visualstudio/ide/managing-application-settings-dotnet).

**Comment by wiiutitlekeys** [comment]
Alright! Thank you for your help.
