### ISSUE TITLE
How are title.tik and title.cert handled?

### ISSUE THREAD

**Issue by sAnonymou** [FailedShack/USBHelperLauncher#64]
I've developing my client for android and using JNUSlib, but I've faced with issue when title.tik and title.cert aren't downloaded from the server and that returns 404 for this files. I've checked your code, but I don't understand where you redirect requests from original helper, please, could you share knowledge?

**Comment by FailedShack** [comment]
These requests are mostly pass-through. You might have more luck looking at decompiled Wii U USB Helper code. Albeit something like JNUSTool or FunkiiU might be wiser.
