### ISSUE TITLE
donation key not approved

### ISSUE THREAD

**Issue by leuldereje** [FailedShack/USBHelperLauncher#7]
i used the launcher to generate a donation key buy all i get is donation key not approved when i click i have donation key.

**Comment by FailedShack** [comment]
@leuldereje This is not a place to receive support, next time please join our [Discord](https://discord.io/usbhelperlauncher) for that.

Please, follow these steps:
**Step 1.** Look for the launcher's tray icon in the taskbar.
![Tray icon](https://i.imgur.com/NkWT3vk.png)
**Step 2.** Right click it and select 'Report Issue'.
![Report issue](https://i.imgur.com/CmhTI4G.png)
**Step 3.** Paste the link in a message.
