### ISSUE TITLE
Usb helper keeps sending me to youtube

### ISSUE THREAD

**Issue by suzyq92** [FailedShack/USBHelperLauncher#77]
Not sure why but everytime i try to load it it says something silly like usb helper has been drinking all night and is a bit tipsy, then sends me to youtube if i continue. Any fixes out there?

**Comment by FailedShack** [comment]
Either wait out April Fools or dismiss the messages by pressing "No" or the "X" button.
USBHelperLauncher will proceed either way and won't open your browser.
