### ISSUE TITLE
gamecube iso file error code with server

### ISSUE THREAD

**Issue by Solipund** [FailedShack/USBHelperLauncher#88]

**Comment by blawdi** [comment]
I just tried and I still have the error


![zD53O62 1](https://user-images.githubusercontent.com/27147133/182221239-42fd2001-ee6c-46e8-82cc-1b23a5b328ba.png)

**Comment by FailedShack** [comment]
@blawdi Please follow these steps and upload the exported file
https://wiki.agilly1989.xyz/books/wiiu/page/usbhelper-usbhelperlauncher#bkmrk---issue%3A-something-i

**Comment by crimsonnight** [comment]
> @blawdi Please follow these steps and upload the exported file https://wiki.agilly1989.xyz/books/wiiu/page/usbhelper-usbhelperlauncher#bkmrk---issue%3A-something-i

Attached (grabbed after trying to export Double Dash)
[log.zip](https://github.com/FailedShack/USBHelperLauncher/files/9237748/log.zip)

**Comment by blawdi** [comment]
hello thanks u for ur help! 
[blawdi.log](https://github.com/FailedShack/USBHelperLauncher/files/9239729/blawdi.log)
i have rename her in log

**Comment by FailedShack** [comment]
> > @blawdi Please follow these steps and upload the exported file https://wiki.agilly1989.xyz/books/wiiu/page/usbhelper-usbhelperlauncher#bkmrk---issue%3A-something-i
> 
> Attached (grabbed after trying to export Double Dash) [log.zip](https://github.com/FailedShack/USBHelperLauncher/files/9237748/log.zip)

Aha, it seems like Cloudflare had cached the failure. It should actually work now.

**Comment by crimsonnight** [comment]
It seems to be working now, thanks - I don't want to derail this thread, but is there a way to import saves into converted games?

**Comment by Masamune3210** [comment]
If I'm not mistaken it would be the same as any normal game that uses the emulator, if its using the official one it gets injected into the title's save directory and if its using nintendont it goes on the sd card in the correct folder
