### ISSUE TITLE
Windows Defender blocked Version 1.0

### ISSUE THREAD

**Issue by VixiKitsune** [FailedShack/USBHelperLauncher#91]
Said it found severe trojans after updating.

**Comment by Masamune3210** [comment]
False positive, defender is drunk as usual. Trust me, if malware was being distributed in something as widely used as this, it would be very loudly being yelled about.

**Comment by FailedShack** [comment]
Yes, it's a false positive. It's not the first time that we've had a build mistakenly flagged as "Trojan:Script/Wacatac.B!ml".
However, this morning as I was collecting data to submit an incorrect detection report, I updated my Windows Defender definitions and apparently it is not longer being flagged on my machine. Please update your definitions and let me know if this has been fixed.

**Comment by VixiKitsune** [comment]
Ran the definition update and it seems to be fixed on my end.

**Comment by FailedShack** [comment]
Well, that was a quick turnaround. Glad I didn't need to send them a report this time :smile:
